[build]
  command = "npm run build:prod"
  publish = "dist/demo/browser"

[build.environment]
  NODE_VERSION = "18.20.0"

[[plugins]]
  package = "@netlify/angular-runtime"
  inputs = { disabled = true }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

