[build]
  command = "npm run build:prod"
  publish = "dist/demo/browser/browser"


[build.environment]
  NODE_VERSION = "18.20.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force; let existing files (JS/CSS) be served normally

